### ISSUE TITLE
globalWatchers.append & filtering not synced via globalWatcherQueue

### ISSUE THREAD

**Issue by zrzka** [steipete/InterposeKit#8]
Quickly checked the code and I'm wondering ...

Global image watcher utilizes the `globalWatcherQueue` queue to filter `globalWatchers`:

https://github.com/steipete/InterposeKit/blob/62783468cc49b6b82d08a67905eaf75f22aacef9/Sources/InterposeKit/InterposeKit.swift#L270

But there's another place where this queue isn't used, access to `globalWatchers` is not synced:

https://github.com/steipete/InterposeKit/blob/62783468cc49b6b82d08a67905eaf75f22aacef9/Sources/InterposeKit/InterposeKit.swift#L242

Additional thing is that the `globalWatchers.append(self)` should be probably replaced by the `InterposeWatcher.append(...)` to encapsulate this whole watching stuff (`globalWatchers`).

**Comment by steipete** [comment]
Spot on! Fixing...
